export default {
  searchIsFocus: false,
  searchInput: '',
  isUserPopup: false,
  user: {
    avatar: 'https://www.w3schools.com/howto/img_avatar2.png',
  },
  navigationItems: [
    { id: 'dashboard', label: 'dashboard' },
    { id: 'agent', label: 'agent' },
    { id: 'myCruise', label: 'my cruise' },
    { id: 'help', label: 'help' },
  ],
  histories: [1, 2, 3, 4, 5, 6].map(() => 'bjstdmngbgr02/Acceptance_test'),
  status: {
    building: { title: 'building', count: 3 },
    idle: { title: 'idle', count: 5 },
  },
  types: {
    all: { title: 'all', count: 8 },
    physical: { title: 'physical', count: 5 },
    virtual: { title: 'virtual', count: 3 },
  },
  currentSearchType: 'all',
  browserIndex: [
    { id: 1, name: 'Firefox' },
    { id: 2, name: 'Safari' },
    { id: 3, name: 'Opera' },
    { id: 4, name: 'Ubuntu' },
    { id: 5, name: 'Chrome' },
    { id: 6, name: 'IE' },
    { id: 7, name: 'Edge' },
  ],
  sessions: [{
    id: 0,
    status: 'building',
    ip: '192.168.0.102',
    type: 'windows',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [1, 2, 3],
    isEditing: false,
    addingResource: '',
  }, {
    id: 1, 
    status: 'idle',
    ip: '192.168.0.102',
    type: 'windows',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [1, 2],
    isEditing: false,
    addingResource: '',
  }, {
    id: 2, 
    status: 'idle',
    ip: '192.168.1.92',
    type: 'ubuntu',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [1, 2, 3],
    isEditing: false,
    addingResource: '',
  }, {
    id: 3, 
    status: 'building',
    ip: '192.168.1.92',
    type: 'redhat',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [2, 3],
    isEditing: false,
    addingResource: '',
  }, {
    id: 4, 
    status: 'idle',
    ip: '192.168.1.92',
    type: 'debian',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [1, 3, 2],
    isEditing: false,
    addingResource: '',
  }, {
    id: 5, 
    status: 'idle',
    ip: '192.168.1.92',
    type: 'ubuntu',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [1, 3, 2],
    isEditing: false,
    addingResource: '',
  }, {
    id: 6, 
    status: 'idle',
    ip: '192.168.1.92',
    type: 'windows',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [1, 3, 2],
    isEditing: false,
    addingResource: '',
  }, {
    id: 7, 
    status: 'idle',
    ip: '192.168.1.92',
    type: 'ubuntu',
    url: 'bjstwojfd.thoughtworks.com',
    path: '/var/lib/cruise-agent',
    browsers: [1, 3, 2],
    isEditing: false,
    addingResource: '',
  }],
} 
